### ISSUE TITLE
hello 

### ISSUE THREAD

**Issue by Nathmatt22** [ThePython10110/better_command_blocks#1]
I can't place an order, it doesn't work, I'm bad

**Comment by ThePython10110** [comment]
You need to have the `better_command_blocks` privilege to place and use Better Command Blocks.
```
/grantme better_command_blocks
```

**Comment by Nathmatt22** [comment]
I have it but it doesn't work

**Comment by ThePython10110** [comment]
You can't place the command blocks? Or something else?

**Comment by Nathmatt22** [comment]
I can't execute commands so maybe I didn't understand the mods because I'm trying to do /give it doesn't work

**Comment by ThePython10110** [comment]
You're not really giving me enough information for me to help you.
